// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class CashRegisterSession
{
    public int Id { get; set; }

    public int CashRegisterId { get; set; }

    public int? OpenedBy { get; set; }

    public int? ClosedBy { get; set; }

    public decimal OpeningAmount { get; set; }

    public decimal? ClosingAmount { get; set; }

    public DateTime OpeningTime { get; set; }

    public DateTime? ClosingTime { get; set; }

    public bool? Open { get; set; }

    public string? Observations { get; set; }

    public int CompanyId { get; set; }

    public virtual ICollection<CashMovement> CashMovements { get; set; } = new List<CashMovement>();

    public virtual CashRegister CashRegister { get; set; } = null!;

    public virtual User? ClosedByNavigation { get; set; }

    public virtual Company Company { get; set; } = null!;

    public virtual ICollection<InvoicesHeader> InvoicesHeaders { get; set; } = new List<InvoicesHeader>();

    public virtual User? OpenedByNavigation { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}