// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class CashMovement
{
    public int Id { get; set; }

    public int CashRegisterSessionId { get; set; }

    public string MovementType { get; set; } = null!;

    public decimal Amount { get; set; }

    public string? Description { get; set; }

    public int? RelatedInvoiceId { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual CashRegisterSession CashRegisterSession { get; set; } = null!;

    public virtual Company Company { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual InvoicesHeader? RelatedInvoice { get; set; }

    public virtual User? UpdatedByNavigation { get; set; }
}