// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class Company
{
    public int Id { get; set; }

    public int? CorporateGroupId { get; set; }

    public string Name { get; set; } = null!;

    public string? ObjectType { get; set; }

    public string? Phone1 { get; set; }

    public string? Phone2 { get; set; }

    public string? CountryCode { get; set; }

    public string? Email { get; set; }

    public string? Address { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public string? FiscalId { get; set; }

    public virtual ICollection<Barcode> Barcodes { get; set; } = new List<Barcode>();

    public virtual ICollection<CashMovement> CashMovements { get; set; } = new List<CashMovement>();

    public virtual ICollection<CashRegisterSession> CashRegisterSessions { get; set; } = new List<CashRegisterSession>();

    public virtual ICollection<CashRegister> CashRegisters { get; set; } = new List<CashRegister>();

    public virtual User? CreatedByNavigation { get; set; }

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<InvoicesDetail> InvoicesDetails { get; set; } = new List<InvoicesDetail>();

    public virtual ICollection<InvoicesHeader> InvoicesHeaders { get; set; } = new List<InvoicesHeader>();

    public virtual ICollection<Measurement> Measurements { get; set; } = new List<Measurement>();

    public virtual ICollection<PaymentMethod> PaymentMethods { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<ProductsCategory> ProductsCategories { get; set; } = new List<ProductsCategory>();

    public virtual ICollection<ProductsSubCategory> ProductsSubCategories { get; set; } = new List<ProductsSubCategory>();

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual ICollection<Taxe> Taxes { get; set; } = new List<Taxe>();

    public virtual User? UpdatedByNavigation { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<WareHouse> WareHouses { get; set; } = new List<WareHouse>();

    public virtual ICollection<WareHouseEntrance> WareHousesEntrances { get; set; } = new List<WareHouseEntrance>();

    public virtual ICollection<WareHouseExit> WareHousesExits { get; set; } = new List<WareHouseExit>();

    public virtual ICollection<WareHouseTransfer> WareHousesTransfers { get; set; } = new List<WareHouseTransfer>();
}