// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class InvoicesDetail
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? InvoiceHeaderId { get; set; }

    public decimal? Qty { get; set; }

    public decimal? Price { get; set; }

    public int? TaxId { get; set; }

    public string? ProductDescription { get; set; }

    public string? ProductCode { get; set; }

    public decimal Discount { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? ItbisTotal { get; set; }

    public int CompanyId { get; set; }

    public virtual Company Company { get; set; } = null!;

    public virtual InvoicesHeader? InvoiceHeader { get; set; }

    public virtual Product? Product { get; set; }

    public virtual Taxe? Tax { get; set; }
}