// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class InvoicesHeader
{
    public int Id { get; set; }

    public DateTime Date { get; set; }

    public decimal? Total { get; set; }

    public decimal? SubTotal { get; set; }

    public decimal? GeneralAmount { get; set; }

    public int? UserId { get; set; }

    public string Status { get; set; } = null!;

    public int? CustomerId { get; set; }

    public string? ClientRnc { get; set; }

    public string? ClientName { get; set; }

    public int? CashRegisterSessionId { get; set; }

    public int? SucursalId { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<CashMovement> CashMovements { get; set; } = new List<CashMovement>();

    public virtual CashRegisterSession? CashRegisterSession { get; set; }

    public virtual Company Company { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual Customer? Customer { get; set; }

    public virtual ICollection<InvoicesDetail> InvoicesDetails { get; set; } = new List<InvoicesDetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User? UpdatedByNavigation { get; set; }

    public virtual User? User { get; set; }
}