// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int PaymentMethodId { get; set; }

    public int InvoiceHeaderId { get; set; }

    public int? CashRegisterSessionId { get; set; }

    public decimal Amount { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual CashRegisterSession? CashRegisterSession { get; set; }

    public virtual Company Company { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual InvoicesHeader InvoiceHeader { get; set; } = null!;

    public virtual PaymentMethod PaymentMethod { get; set; } = null!;

    public virtual User? UpdatedByNavigation { get; set; }
}