// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Code { get; set; } = null!;

    public decimal Price { get; set; }

    public string? BarCode { get; set; }

    public int CategoryId { get; set; }

    public int MeasurementId { get; set; }

    public bool? IsActive { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; } = null;

    public int? UpdatedBy { get; set; } = null;

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Barcode> Barcodes { get; set; } = new List<Barcode>();

    public virtual ProductsCategory? Category { get; set; } = null!;
    
    public virtual Company? Company { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual ICollection<InvoicesDetail> InvoicesDetails { get; set; } = new List<InvoicesDetail>();
    
    public virtual Measurement? Measurement { get; set; } = null!;

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual User? UpdatedByNavigation { get; set; }

    public virtual ICollection<WareHouseEntrance> WareHousesEntrances { get; set; } = new List<WareHouseEntrance>();

    public virtual ICollection<WareHouseExit> WareHousesExits { get; set; } = new List<WareHouseExit>();

    public virtual ICollection<WareHouseTransfer> WareHousesTransfers { get; set; } = new List<WareHouseTransfer>();
}