// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class Role
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int CompanyId { get; set; }

    public virtual Company Company { get; set; }

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
    public virtual ICollection<User> Users { get; set; } = [];
    public virtual ICollection<UserRole> UsersRoles { get; set; } = [];

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}