// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class User
{
    public int Id { get; set; }

    public string Name { get; set; }
    public DateTime? BirthDate { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public int? CompanyId { get; set; }

    public virtual ICollection<CashMovement> CashMovementCreatedByNavigations { get; set; } = new List<CashMovement>();

    public virtual ICollection<CashMovement> CashMovementUpdatedByNavigations { get; set; } = new List<CashMovement>();

    public virtual ICollection<CashRegisterSession> CashRegisterSessionClosedByNavigations { get; set; } = new List<CashRegisterSession>();

    public virtual ICollection<CashRegisterSession> CashRegisterSessionOpenedByNavigations { get; set; } = new List<CashRegisterSession>();

    public virtual Company Company { get; set; }
    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<User> UsersCreatedByNavigations { get; set; } = [];

    public virtual ICollection<User> UsersUpdatedByNavigations { get; set; } = [];
    public virtual User UpdatedByNavigation { get; set; }
    public virtual ICollection<Role> Roles { get; set; } = [];
    public virtual ICollection<UserRole> UsersRoles { get; set; } = [];

    public virtual ICollection<Company> CompanyCreatedByNavigations { get; set; } = new List<Company>();

    public virtual ICollection<Company> CompanyUpdatedByNavigations { get; set; } = new List<Company>();

    public virtual ICollection<Customer> CustomerCreatedByNavigations { get; set; } = new List<Customer>();

    public virtual ICollection<Customer> CustomerUpdatedByNavigations { get; set; } = new List<Customer>();

    public virtual ICollection<InvoicesHeader> InvoicesHeaderCreatedByNavigations { get; set; } = new List<InvoicesHeader>();

    public virtual ICollection<InvoicesHeader> InvoicesHeaderUpdatedByNavigations { get; set; } = new List<InvoicesHeader>();

    public virtual ICollection<InvoicesHeader> InvoicesHeaderUsers { get; set; } = new List<InvoicesHeader>();

    public virtual ICollection<Measurement> MeasurementCreatedByNavigations { get; set; } = new List<Measurement>();

    public virtual ICollection<Measurement> MeasurementUpdatedByNavigations { get; set; } = new List<Measurement>();

    public virtual ICollection<Payment> PaymentCreatedByNavigations { get; set; } = new List<Payment>();

    public virtual ICollection<PaymentMethod> PaymentMethodCreatedByNavigations { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<PaymentMethod> PaymentMethodUpdatedByNavigations { get; set; } = new List<PaymentMethod>();

    public virtual ICollection<Payment> PaymentUpdatedByNavigations { get; set; } = new List<Payment>();

    public virtual ICollection<Permission> PermissionCreatedByNavigations { get; set; } = new List<Permission>();

    public virtual ICollection<Permission> PermissionUpdatedByNavigations { get; set; } = new List<Permission>();

    public virtual ICollection<Product> ProductCreatedByNavigations { get; set; } = new List<Product>();

    public virtual ICollection<Product> ProductUpdatedByNavigations { get; set; } = new List<Product>();

    public virtual ICollection<ProductsCategory> ProductsCategoryCreatedByNavigations { get; set; } = new List<ProductsCategory>();

    public virtual ICollection<ProductsCategory> ProductsCategoryUpdatedByNavigations { get; set; } = new List<ProductsCategory>();

    public virtual ICollection<ProductsSubCategory> ProductsSubCategoryCreatedByNavigations { get; set; } = new List<ProductsSubCategory>();

    public virtual ICollection<ProductsSubCategory> ProductsSubCategoryUpdatedByNavigations { get; set; } = new List<ProductsSubCategory>();

    public virtual ICollection<RolePermission> RolePermissionCreatedByNavigations { get; set; } = new List<RolePermission>();

    public virtual ICollection<RolePermission> RolePermissionUpdatedByNavigations { get; set; } = new List<RolePermission>();

    public virtual ICollection<Stock> StockCreatedByNavigations { get; set; } = new List<Stock>();

    public virtual ICollection<Stock> StockUpdatedByNavigations { get; set; } = new List<Stock>();

    public virtual ICollection<Taxe> TaxisCreatedByNavigations { get; set; } = new List<Taxe>();

    public virtual ICollection<Taxe> TaxisUpdatedByNavigations { get; set; } = new List<Taxe>();

    public virtual ICollection<UserRole> UserRoleCreatedByNavigations { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUpdatedByNavigations { get; set; } = new List<UserRole>();

    public virtual ICollection<UserRole> UserRoleUsers { get; set; } = new List<UserRole>();

    public virtual ICollection<WareHouse> WareHouseCreatedByNavigations { get; set; } = new List<WareHouse>();

    public virtual ICollection<WareHouse> WareHouseUpdatedByNavigations { get; set; } = new List<WareHouse>();

    public virtual ICollection<WareHouseEntrance> WareHousesEntranceCreatedByNavigations { get; set; } = new List<WareHouseEntrance>();

    public virtual ICollection<WareHouseEntrance> WareHousesEntranceUpdatedByNavigations { get; set; } = new List<WareHouseEntrance>();

    public virtual ICollection<WareHouseExit> WareHousesExitCreatedByNavigations { get; set; } = new List<WareHouseExit>();

    public virtual ICollection<WareHouseExit> WareHousesExitUpdatedByNavigations { get; set; } = new List<WareHouseExit>();

    public virtual ICollection<WareHouseTransfer> WareHousesTransferCreatedByNavigations { get; set; } = new List<WareHouseTransfer>();

    public virtual ICollection<WareHouseTransfer> WareHousesTransferUpdatedByNavigations { get; set; } = new List<WareHouseTransfer>();

}