// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class WareHouseEntrance
{
    public int Id { get; set; }

    public int WareHouseId { get; set; }

    public DateTime? Date { get; set; }

    public string? Description { get; set; }

    public int ProductId { get; set; }

    public decimal Qty { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Company Company { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual Product Product { get; set; } = null!;

    public virtual User? UpdatedByNavigation { get; set; }

    public virtual WareHouse WareHouse { get; set; } = null!;
}