// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace SELLVAPI.DataAccess.Models;

public partial class WareHouse
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Location { get; set; }

    public bool? IsActive { get; set; }

    public decimal? MinStock { get; set; }

    public decimal? MaxStock { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Company Company { get; set; } = null!;

    public virtual User? CreatedByNavigation { get; set; }

    public virtual ICollection<Stock> Stocks { get; set; } = new List<Stock>();

    public virtual User? UpdatedByNavigation { get; set; }

    public virtual ICollection<WareHouseEntrance> WareHousesEntrances { get; set; } = new List<WareHouseEntrance>();

    public virtual ICollection<WareHouseExit> WareHousesExits { get; set; } = new List<WareHouseExit>();

    public virtual ICollection<WareHouseTransfer> WareHousesTransferToWareHouses { get; set; } = new List<WareHouseTransfer>();

    public virtual ICollection<WareHouseTransfer> WareHousesTransferWareHouses { get; set; } = new List<WareHouseTransfer>();
}