// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS_VET_API.DataAccess.Models;

public partial class Barcode
{
    public int Id { get; set; }

    public string Code { get; set; }

    public int? ProductId { get; set; }

    public int CompanyId { get; set; }

    public virtual Company Company { get; set; }

    public virtual Product Product { get; set; }
}