// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS_VET_API.DataAccess.Models;

public partial class CashRegister
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public bool? IsActive { get; set; }

    public int CompanyId { get; set; }

    public virtual ICollection<CashRegisterSession> CashRegisterSessions { get; set; } = new List<CashRegisterSession>();

    public virtual Company Company { get; set; }
}