// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS_VET_API.DataAccess.Models;

public partial class RolePermission
{
    public int RoleId { get; set; }

    public int PermissionId { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Company Company { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Permission Permission { get; set; }

    public virtual Role Role { get; set; }

    public virtual User UpdatedByNavigation { get; set; }
}