// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POS_VET_API.DataAccess.Models;

public partial class UsersToken
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Token { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpDate { get; set; }
}