// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace POS_VET_API.DataAccess.Models;

public partial class UserRole
{
    public int UserId { get; set; }

    public int RoleId { get; set; }

    public int CompanyId { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CreatedAt { get; set; }
    [JsonIgnore]
    public virtual Company Company { get; set; }
    [JsonIgnore]
    public virtual User CreatedByNavigation { get; set; }
    [JsonIgnore]
    public virtual Role Role { get; set; }
    [JsonIgnore]
    public virtual User UpdatedByNavigation { get; set; }
    [JsonIgnore]
    public virtual User User { get; set; }
}